# Stage 1: Build
FROM golang:{{.GoVersion}} AS builder

# Making working dir
WORKDIR /app

# Copy go.mod and go.sum and installing dependencies
COPY go.mod go.sum* ./
RUN go mod download

# Copy code
COPY . .

# Building binary
RUN CGO_ENABLED=0 go build -o main .

# Stage 2: Run
FROM gcr.io/distroless/static-debian12

# Making working dir
WORKDIR /app

# Copy binary file from first stage
COPY --from=builder /app/main .

# App runner
CMD ["./main"]
